#workflow에 이름붙이는법
name: Github Actions 실행시켜보기
#event: 실행되는 시점설정
#main이라는 브랜치에 push될때 아래 workflow실행
on:
  push:
    branches:
      - main
#하나의 workflow는 반드시 1개이상의 job으로구성
jobs:
  My-Deploy-Job:
    #ubuntu 환경 / 가장 최신버전
    runs-on: ubuntu-latest
    #step: 작업수행하는 가장작은 단위
    #하나의 job은 여러 steps로 구성
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러명령어 문장 작성하기
        run: |
          echo "Good"
          echo "morning"

      - name: Gihub Actions 자체 저장되어있는 변수 사용하기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 아무한테도 노출되면 안되는 값
        run: |
          echo ${{ secrets.MY_NAME}}
          echo ${{ secrets.MY_HOBBY}}