#workflow에 이름붙이는법
name: Github Actions 실행시켜보기
#event: 실행되는 시점설정
#main이라는 브랜치에 push될때 아래 workflow실행
on:
  push:
    branches:
      - main
#하나의 workflow는 반드시 1개이상의 job으로구성
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hello World"